name: Cancel workflows

on: [push, pull_request_target]

env:
  TZ: Europe/Berlin

jobs:
  cancel:
    name: "Cancel previous runs"
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          workflow_id: 2235184 # GitHub ID for .github/workflows/ci.yml
          access_token: ${{ github.token }}
