name: Cancel workflows

on: [push, pull_request_target]

env:
  TZ: Europe/Berlin

jobs:
  cancel:
    name: "Cancel previous runs"
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          workflow_id: ci_linux.yml, ci_macos.yml, ci_win.yml, ci_icc.yml, ci.yml
          all_but_latest: true
          access_token: ${{ github.token }}
